### ISSUE TITLE
Consider releasing 1.0.0

### ISSUE THREAD

**Issue by rarkins** [conventional-changelog/conventional-commits-detector#3]
Is there anything standing in the way of making a 1.0.0 release for this module? As per semver.org:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

I have battle-tested this library in [renovate](https://github.com/renovateapp/renovate), it hasn't needed an update for 18+ months, and has no outstanding functional issues. Unless you plan to deprecate it, it would be great to see a v1.0.0 to indicate the API won't change without a major version bump.

**Comment by hbetts** [comment]
@rarkins I will release a 1.0.0 as soon as I'm able to.

It is also actively used in my own release tools, and I don't see it being deprecated (It falls into the category of projects that are feature complete, so there just isn't much purpose to create new releases)

**Comment by hbetts** [comment]
@Tapppi @bcoe @stevemao would one of y'all be willing to add this package to the `conventional-changelog` organization on the npmjs registry so that I can then publish version 1.0?

**Comment by hbetts** [comment]
@Tapppi @bcoe @stevemao ping. Can one of you please add this package to the `conventional-changelog` organization on the npmjs registry please?

**Comment by hbetts** [comment]
Version 1.0.0 has been published.
